# Generated by Django 4.0.4 on 2022-05-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
