# Generated by Django 4.0.4 on 2022-05-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer',
        ),
    ]
