# Generated by Django 4.0.4 on 2022-05-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live_sale',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=100)),
                ('terms_and_cond', models.CharField(max_length=100)),
            ],
        ),
    ]
