# Generated by Django 4.0.4 on 2022-05-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_live_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer1',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='offer2',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='offer3',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='offer4',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
